cookie:
  expiry_days: 1
  key: key_sistere
  last_date: null
  name: cookie_sistere
credentials:
  usernames:
    brei:
      email: bryan.a.r.g.98@gmail.com
      first_name: Bryan
      id: 1
      last_login: '2025-01-22T17:37:29.076663-05:00'
      last_name: Reinoso
      logged_in: true
      roles:
      - admin
      - user
      - viewer
