cookie:
  expiry_days: 1
  key: key_sistere
  last_date: null
  name: cookie_sistere
credentials:
  usernames:
    anfernas:
      email: and@fer.com
      first_name: Andres
      id: 2
      last_login: null
      last_name: Fernandez
      logged_in: false
      roles:
      - user
    brei:
      email: bryan.a.r.g.98@gmail.com
      first_name: Bryan
      id: 1
      last_login: '2025-01-16T10:25:27.444020-05:00'
      last_name: Reinoso
      logged_in: true
      roles:
      - admin
      - user
      - viewer
    rein:
      email: rei@tia.com
      first_name: reino
      id: 12
      last_login: null
      last_name: so
      logged_in: false
      roles:
      - user
    santi:
      email: san@tia.com
      first_name: santi
      id: 11
      last_login: null
      last_name: AGO
      logged_in: false
      roles:
      - user
